# Generated by Django 3.2.9 on 2021-11-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Resease', models.DateField()),
                ('Plot', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Rating', models.IntegerField()),
                ('Comment', models.CharField(max_length=500)),
            ],
        ),
    ]
