# Generated by Django 3.2.9 on 2021-11-13 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0002_rename_resease_movies_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='Movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.movies'),
            preserve_default=False,
        ),
    ]
