# Generated by Django 3.2.9 on 2021-11-13 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0003_auto_20211113_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Poster',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.users'),
            preserve_default=False,
        ),
    ]
