# Generated by Django 3.2.9 on 2021-11-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_auto_20211113_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='IsAdmin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
